version: '3'

networks:
  api_network:
services:
  scaping_api:
    build: .
    container_name: scaping_api
    hostname: scaping_api
    image: scaping_api
    restart: always
    environment:
      - TZ=Asia/Bangkok 
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - api_network
 
   


