version: '3.8'

services:
  nodejs:
    container_name: nodejs_puppeteer
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '3000:3000'
    networks:
      - puppeteer-network

networks:
  puppeteer-network:
    name: puppeteer-network
